### ISSUE TITLE
Process not ending after UI close on MacOsX

### ISSUE THREAD

**Issue by siriux** [Srinivasa314/alcro#3] opened 2020-05-22 17:31 UTC
I've tried it on windows and macosx and the example seems to work on both, but on macosx the process is not ending after the window is closed.

**Comment by Srinivasa314** [comment] 2020-05-23 04:45
Check branch issue3 and see if it is fixed

**Comment by Srinivasa314** [comment] 2020-05-24 10:43
Merged it to master. Check if the issue is resolved now.

**Comment by Srinivasa314** [comment] 2020-05-27 05:13
Reopen the issue if it still exists

**Closed as completed by Srinivasa314** 2020-05-27 05:13 UTC
